# Generated by Django 4.2 on 2023-04-09 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_beds', '0007_typeofaccommodation_alter_hospital_name_healthunits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthunits',
            options={'verbose_name': 'Unidade de saúde', 'verbose_name_plural': 'Unidades de saúde'},
        ),
        migrations.AlterModelOptions(
            name='typeofaccommodation',
            options={'verbose_name': 'Tipo de acomodação', 'verbose_name_plural': 'Tipos de acomodação'},
        ),
        migrations.AddField(
            model_name='healthunits',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='healthunits',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='hospitalBeds',
            fields=[
                ('id', models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Identificação')),
                ('name', models.CharField(max_length=25, verbose_name='Nome do leito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('extra', models.BooleanField(default=False, verbose_name='Extra')),
                ('status', models.CharField(choices=[('BLOQUEADO', 'BLOQUEADO'), ('OCUPADO', 'OCUPADO'), ('VAGO', 'VAGO')], max_length=45, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('health_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_beds.healthunits', verbose_name='Unidade de saúde')),
            ],
            options={
                'verbose_name': 'Leito',
                'verbose_name_plural': 'Leitos',
            },
        ),
    ]
