# Generated by Django 4.2 on 2023-04-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_is_admin_users_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
