# Generated by Django 4.2 on 2023-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Identificação')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('acronym', models.CharField(blank=True, max_length=45, null=True, verbose_name='Sigla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
    ]
