# Generated by Django 4.2 on 2023-04-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_beds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitais'},
        ),
    ]
