# Generated by Django 4.2 on 2023-04-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_beds', '0008_alter_healthunits_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalbeds',
            old_name='extra',
            new_name='is_extra',
        ),
        migrations.AddField(
            model_name='hospitalbeds',
            name='is_isolation',
            field=models.BooleanField(default=False, verbose_name='Isolamento'),
        ),
    ]
